name: stroll_dev_test
description: "Stroll Dev Test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/italic.otf
          style: italic
        - asset: assets/fonts/bold.otf
          weight: 700
        - asset: assets/fonts/semibold.otf
          weight: 600
        - asset: assets/fonts/regular.otf
